import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/roboto-mono"; // Defaults to weight 400
import "@fontsource/roboto-mono/300.css"; // Specify weight
import "@fontsource/roboto-mono/300-italic.css"; // Specify weight and style
import { Providers } from "./provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <div className="flex max-w-4xl m-auto flex-col min-h-screen">
          <Providers>
            <Header />
            <Providers>{children}</Providers>
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
